FROM node:23-slim

WORKDIR /app

ARG VITE_GET_API_URL
RUN echo $VITE_GET_API_URL

COPY package*.json ./

RUN npm install 

RUN npm install -g serve

COPY ./ /app/

RUN npm run build

EXPOSE 3000

CMD [ "serve", "-s", "dist" ]

# CMD serve -s build -l 5173
