services:
  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
      dockerfile: ./dockerfile
      args:
        - VITE_GET_API_URL=http://127.0.0.1:8080
    # platform: linux/amd64
    restart: always
    ports:
      - "3000:3000"
    expose:
      - 3000

  backend:
    container_name: "backend"
    build:
      context: ./backend
      dockerfile: ./dockerfile
    # platform: linux/amd64
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 8080
